/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.objecttrouve.keycloak.testcontainers.issues.gradleworkingdir;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
